site_name: Sani 文档

repo_url: https://github.com/Wybxc/sani
repo_name: Wybxc/sani
edit_uri: ''
copyright: Copyright &copy; Wybxc 2022.

theme:
  name: material
  language: zh
  features:
    - navigation.indexes
    - toc.follow
    - navigation.top
    - header.autohide
    - content.code.annotate
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: 切换到黑暗模式
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: 切换到明亮模式
  icon:
    repo: fontawesome/brands/github
    logo: material/curtains
  favicon: _assets/images/favicon.png
extra_css:
  - _assets/extra/heti.css
  - _assets/extra/extra.css
extra_javascript:
  - _assets/extra/heti.js
  - _assets/extra/extra.js

watch:
  - sani

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      custom_templates: docs/_assets/overrides
      handlers:
        python:
          import:
            - https://docs.python.org/zh-cn/3/objects.inv
          options:
            heading_level: 2
            show_root_heading: no
            members_order: source
            docstring_style: google
            show_submodules: no
            show_bases: no
            show_source: yes
            show_signature_annotations: yes
            separate_signature: yes
            docstring_section_style: table
            line_length: 80

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.snippets
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.keys
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - codehilite:
      guess_lang: true
      linenums: true
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.magiclink:
      repo_url_shorthand: true
      social_url_shorthand: true
      repo_url_shortener: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
