name: Document
on:
  push:
    branches: [master, main]
jobs:
  Mkdocs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: 3.9

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up netlify cli
        run: npm install -g netlify-cli

      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install dependencies
        run: |
          pdm sync -d -G doc

      - name: Build document
        run: |
          pdm run -v mkdocs build

      - name: Deploy to netlify
        run: netlify deploy --dir=site --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
